import React from "react"
import Head from 'next/head'
import { PostCard, Categories, PostWidget } from "../components/index.js";
import { getPosts } from "../services";
// import Image from 'next/image'
// import styles from '../styles/Home.module.css';

// const posts = [
//   {title: 'React Testing', excerpt: 'Learn React Testing' },
//   {title: 'React with Tailwind', excerpts: 'Learn React with Tailwind' },
// ];

// fetch data from graphqlcms
export async function getStaticProps() {

  const posts = await getPosts();

  // const posts = (await getPosts()) || [];

  return {
    props: { posts }
  }
}

export default function Home({ posts }) {

  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>
          Conversate Blog - Get to flows 
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post) => (
              <PostCard post={post.node} key={post.title} />
          ))}
        </div>

        <div className="lg:col-span-4 col-span-1">
            <div className="lg:sticky relatve top-8">
              <PostWidget /> 
              <Categories />                  
            </div>
        </div>
      </div>

      



    </div>
  )
}
